apiVersion: v2
name: ai-chatclient-backend
description: AI ChatBot Client - Hono API with PostgreSQL
dependencies:
  - name: application
    repository: oci://registry.netic.dk/cloudfactory
    version: 1.0.48
type: application
version: 3.0.0
appVersion: "3.0.0"
